apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ instance_name }}-miracle-service
  labels:
    app: {{ instance_name }}-miracle-service
spec:
  selector:
    matchLabels:
      app: {{ instance_name }}-miracle-service
  template:
    metadata:
      name: {{ instance_name }}-miracle-service
      labels:
        app: {{ instance_name }}-miracle-service
    spec:
      containers:
      - name: {{ instance_name }}-miracle-service
        image: {{ miracle-service.image }}
        ports:
        - containerPort: 8080 # 容器端口
        resources:
          limits:
            cpu: "0.1" # cpu 限制
            memory: "800Mi" # 内存限制
          requests:
            cpu: "0.1" # cpu 预留（与限制值一致）
            memory: "800Mi" # 内存预留（与限制值一致）
---
apiVersion: v1
kind: Service
metadata:
  name: {{ instance_name }}-miracle-service
spec:
  type: NodePort
  ports:
  - port: 8080 # 服务端口
    nodePort: 31388
  selector:
    app: {{ instance_name }}-miracle-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ instance_name }}-miracle-ui
  labels:
    app: {{ instance_name }}-miracle-ui
spec:
  selector:
    matchLabels:
      app: {{ instance_name }}-miracle-ui
  template:
    metadata:
      name: {{ instance_name }}-miracle-ui
      labels:
        app: {{ instance_name }}-miracle-ui
    spec:
      containers:
      - name: {{ instance_name }}-miracle-ui
        image: {{ miracle-ui.image }}
        ports:
        - containerPort: 80 # 容器端口
        resources:
          limits:
            cpu: "0.1" # cpu 限制
            memory: "800Mi" # 内存限制
          requests:
            cpu: "0.1" # cpu 预留（与限制值一致）
            memory: "800Mi" # 内存预留（与限制值一致）
---
apiVersion: v1
kind: Service
metadata:
  name: {{ instance_name }}-miracle-ui
spec:
  type: NodePort
  ports:
  - port: 80 # 服务端口
    nodePort: 31380
  selector:
    app: {{ instance_name }}-miracle-ui